#!/usr/bin/python
import os
import sys
import subprocess
import cgi
import string
import shutil
import random
import ctypes
from ctypes import cdll
apparmor = cdll.LoadLibrary('/usr/lib/libapparmor.so')

#if apparmor.aa_change_profile("restricted_books".encode('utf-8')):
#  print("Armor error")
#  sys.exit(1)

# parse query string
qs = cgi.FieldStorage()
if 'title' not in qs:
  print("Error")
  sys.exit(1)
title = qs['title'].value
if not os.path.isfile('books/' + title):
  print("Bad title")
  sys.exit(1)

# launch ebook-convert
# sadly it uses an output filename to determine type
# and it's stdout and stderr aren't clean.
# A symlink with mobi extension to /dev/stdout isn't viable.
# So I export to a random filename and delete it after shooting it to stdout.
filename = ''.join(random.choice(string.ascii_lowercase) for i in range(8))
filename = "tmp/{}.mobi".format(filename)

p = subprocess.run(
  ["ebook-convert", "books/" + title, filename],
  check=True, capture_output=True)

print("Content-Type: application/x-mobipocket-ebook\n")
sys.stdout.flush()
with open(filename, "rb") as f: shutil.copyfileobj(f, sys.stdout.buffer)
os.remove(filename)
