#!/usr/bin/python
import os
import re

# https://stackoverflow.com/questions/4813061/non-alphanumeric-list-order-from-os-listdir
def sorted_aphanumeric(data):
  convert = lambda text: int(text) if text.isdigit() else text.lower()
  alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
  return sorted(data, key=alphanum_key)

# header
print("""<!DOCTYPE html>
<html>
<head>
<title>Test</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
img { min-width: 100%; max-width: 100%; height: auto; }
</style>
</head>
<body>""")

# list of available books
path = "books"
files = sorted_aphanumeric(os.listdir(path))
for title in files:
  if not os.path.isdir(path + '/' + title): continue
  print('<a href="view?page={1}&fit={2}&title={0}">{0}</a><br/>'.format(title, 1, "no"))

# footer
print("""</body>
</html>""")

