#!/usr/bin/python
import os
import re
import struct
import ctypes
from ctypes import cdll
apparmor = cdll.LoadLibrary('/usr/lib/libapparmor.so')

if apparmor.aa_change_profile("restricted_books".encode('utf-8')):
  print("Armor error")
  sys.exit(1)

# https://stackoverflow.com/questions/4813061/non-alphanumeric-list-order-from-os-listdir
def sorted_aphanumeric(data):
  convert = lambda text: int(text) if text.isdigit() else text.lower()
  alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
  return sorted(data, key=alphanum_key)

# header
print("""<!DOCTYPE html>
<html>
<head>
<title>Intranet Books</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/svg+xml" href="icon.svg">
<style>
img { min-width: 100%; max-width: 100%; height: auto; }
html { font-size: 1.75em; }
</style>
</head>
<body>""")

# list of available books
path = "books"
files = sorted_aphanumeric(os.listdir(path))
for title in files:
  if not os.path.isdir(path + '/' + title): continue
  print('<a href="view?page={1}&fit={2}&title={0}">{0}</a>'.format(title, 1, "no"))

  # resume link
  if os.path.isfile('progress/' + title):
    with open('progress/' + title, mode='rb') as f:
      page = struct.unpack("i", f.read(4))[0]
      if page > 1:
        max_page = len(os.listdir('books/' + title))
        print('<a href="view?page={1}&fit={2}&title={0}">(Resume {3:1.0f}%)</a>'.format(title, page, "no", (page - 1) / (max_page - 1) * 100))

  print('<br/>')

# footer
print("""</body>
</html>""")

