#!/usr/bin/python
import os
import sys
import cgi
import struct
import ctypes
from ctypes import cdll
apparmor = cdll.LoadLibrary('/usr/lib/libapparmor.so')

if apparmor.aa_change_profile("restricted_books".encode('utf-8')):
  print("Armor error")
  sys.exit(1)

# parse query string
qs = cgi.FieldStorage()
if 'page' not in qs or 'title' not in qs or 'fit' not in qs:
  print("Error")
  sys.exit(1)
page = int(qs['page'].value)
title = qs['title'].value
fit = qs['fit'].value
if not os.path.isdir('books/' + title):
  print("Bad title")
  sys.exit(1)

# header
print("""<!DOCTYPE html>
<html>
<head>""")
print("<title>{}</title>".format(title))
print("""<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/svg+xml" href="icon.svg">
<style>
* {
  margin: 0.01vh;
  padding: 0.01vh;
}
#progress {
  position: absolute;
  left: 2px;
  top: 2px;
  z-index: 2;
  color:black;
  background-color:#FFFFFF88;
}
""")
if fit == 'yes':
  print('img { max-width: 100%; max-height: 99vh; min-height: 99vh; margin: auto; }')
else:
  print('img { min-width: 100%; max-width: 100%; height: auto; }')
print("""</style>
</head>
<body>""")

# determine image filename format
listing = os.listdir('books/' + title)
sample = listing[0]
# I'm assuming format is XXXXX_00003.jpg
# count digits used
page_index = sample.rfind('_') + 1
count = sample.rfind('.') - page_index

# build image filename
page = int(page)
filename = ("{}{:0>"+str(count)+"d}.jpg").format(sample[0:page_index], page)
next_qs = "page={}&fit={}&title={}".format(page + 1, fit, title)

# save page progress
with open('progress/' + title, mode='wb') as f:
  f.write(struct.pack('i', page))

# view requested page
print('<a href="view?{}"><img src="books/{}/{}" /></a>'.format(next_qs, title, filename))

# page progress
print('<div id="progress">{} / {} ({:1.0f}%)</div>'.format(page, len(listing), (page - 1) / (len(listing) - 1) * 100))

# footer
print("""</body>
</html>""")

